# gemini-1.5-flash / command-r / command-r-plus
model: gemini-1.5-flash
api-key: YOUR_API_KEY
token: YOUR_DISCORD_BOT_TOKEN
trigger: AI,
cleantrig: cleanAI
sysprompt: You are a helpful assistant.
sysfstmsg: Hello! What can I help you?